#!/usr/bin/env python3

import argparse
import platform
import requests
import semantic_version
import shutil
import subprocess
import sys
import urllib.request
from lxml import etree, html
from pathlib import Path


BaseUrl = 'https://download.qt.io/online/qtsdkrepository/'

OsMap = {
  'macos': 'mac_x64',
  'linux': 'linux_x64',
  'windows': 'windows_x86'
}


def key_by_value(dict, value):
  return next((left for left, right in dict.items() if right == value), None)


def decode_version(v):
  v = list(v)
  major = v.pop(0)
  patch = v.pop() if len(v) > 1 else 0
  minor = ''.join(v)
  return semantic_version.Version('{}.{}.{}'.format(major, minor, patch))


def deduce_os():
  os_type = platform.system().lower()
  if os_type == 'darwin':
    os_type = 'macos'
  return os_type


def discover_dirs(url):
  reply = requests.get(url)
  page = html.fromstring(reply.content)
  items = page.xpath('//table//tr[position()>2]//a[not(starts-with(@href, "/"))]/@href')
  return [item for item in items if item.endswith('/')]


def discover_kits(args):
  os_dict = {}
  os_types = discover_dirs(BaseUrl)
  for os_type in os_types:
    human_os = key_by_value(OsMap, os_type[:-1])
    current_os = human_os if human_os is not None else os_type[:-1]
    os_dict[current_os] = None

    if not (args.os == 'discover' and args.all or args.os != 'discover' and args.os in [os_type[:-1], human_os]):
      continue

    targets_dict = {}
    targets = discover_dirs(BaseUrl + os_type)
    targets = [target for target in targets if target != 'root/']
    for target in targets:
      targets_dict[target[:-1]] = None

      if not (args.target == 'discover' and args.all or args.target != 'discover' and args.target == target[:-1]):
        continue

      versions_dict = {}
      versions = discover_dirs(BaseUrl + os_type + target)
      for version in versions:
        if version.startswith('tools_') or version.endswith('_preview/') or version.endswith('_wasm/') or '_src' in version or not version.startswith('qt5_'):
          continue

        ver = decode_version(version[len('qt5_'):-1])
        versions_dict[ver] = None

        if not (args.version == 'discover' and args.all or args.version != 'discover' and args.version == ver):
          continue

        toolchains = discover_dirs(BaseUrl + os_type + target + version)
        toolchains = [toolchain.split('.')[2:] for toolchain in toolchains]
        toolchains = [toolchain[-1] for toolchain in toolchains if len(toolchain) > 0]
        toolchains = set([toolchain[:-1] for toolchain in toolchains if not toolchain.startswith('qt') and not toolchain.startswith('debug')])

        versions_dict[ver] = toolchains

      targets_dict[target[:-1]] = versions_dict

    os_dict[current_os] = targets_dict

  return os_dict


def build_url(args):
  ver = args.version.replace('.', '')
  return BaseUrl + '{}/{}/qt5_{}/'.format(OsMap[args.os], args.target, ver)


def get_info(url, version, toolchain):
  reply = requests.get(url + "Updates.xml")
  update_xml = etree.fromstring(reply.content)

  ver = version.replace('.', '')

  for package in update_xml.xpath('//PackageUpdate'):
    name = package.xpath('Name/text()')[0]
    if name.startswith('qt.') and name.endswith('.{}.{}'.format(ver, toolchain)):
      version = package.xpath('Version/text()')[0]
      archives = package.xpath('DownloadableArchives/text()')[0].split(', ')
      return (name, version, archives)

  print('Update.xml does not contain proper entry for Qt kit', file=sys.stderr)
  return None


def download_and_extract(archives_url, archives):
  for archive in archives:
    try:
      module = archive.split('-')[0]
      print('Downloading module {}... '.format(module), end='', flush=True)
      with urllib.request.urlopen(archives_url + archive) as response, open(archive, 'wb') as out_file:
        shutil.copyfileobj(response, out_file)

      print('\rExtracting module {}... '.format(module), end='', flush=True)
      subprocess.run('7z x {}'.format(archive), shell=True, check=True,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      print('\rInstalled module {} successfully'.format(module))
    except subprocess.CalledProcessError as e:
      print('Error: {}'.format(e))
      raise RuntimeError('Stopped due errors')
    except KeyboardInterrupt:
      print('Interrupted')
      raise KeyboardInterrupt
    finally:
      Path(archive).unlink()

  print('Finished installation')



def main():
  parser = argparse.ArgumentParser(description='Qt downloader',
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)
  parser.add_argument('os', nargs='?', default='discover', help='Operating system type: {}, auto, or discovered one. Omit this to discover available OS types'.format(', '.join(OsMap.keys())))
  parser.add_argument('target', nargs='?', default='discover', help='Target platform. Omit this to discover available targets')
  parser.add_argument('version', nargs='?', default='discover', help='Qt version conforming to Semantic Versioning format: major.minor.patch. Omit this to discover available versions')
  parser.add_argument('toolchain', nargs='?', default='discover', help='Toolchain to use. Omit this to discover available toolchains')
  parser.add_argument('-a', '--all', action='store_true', help='Discover allowed values for all missing arguments')
  args = parser.parse_args()

  if args.os != 'discover':
    if args.os == 'auto':
      args.os = deduce_os()

    print('OS type: {}'.format(args.os))

  if args.target != 'discover':
    print('Target: {}'.format(args.target))

  if args.version != 'discover':
    if not semantic_version.validate(args.version):
      print('Wrong version: {}. Should follow Semantic Versioning format: major.minor.patch\n'.format(args.version), file=sys.stderr)
      parser.print_help()
      sys.exit(1)
    print('Qt version: {}'.format(args.version))

  if args.toolchain != 'discover':
    print('Toolchain: {}'.format(args.toolchain))

  params = [args.os, args.target, args.version, args.toolchain]
  labels = ['OS types', 'targets', 'Qt versions', 'toolchains']
  if 'discover' in params:
    print('Discovering available ', end='')
    
    discoverables = []
    for index, param in enumerate(params):
      if param == 'discover':
        discoverables.append(labels[index])

    if not args.all:
      discoverables = discoverables[:1]

    if len(discoverables) == 1:
      print('{}...'.format(discoverables[0]), end='', flush=True)
    elif len(discoverables) == 2:
      print('{}...'.format(' and '.join(discoverables)), end='', flush=True)
    else:
      print('{}, and {}...'.format(', '.join(discoverables[:-1]), discoverables[-1]), end='', flush=True)

    kits = discover_kits(args)
    print(' Done')

    if args.os == 'discover':
      if not args.all:
        print('  {}'.format(', '.join(sorted(kits.keys()))))
      else:
        for os_type, targets in kits.items():
          print('  {}:'.format(os_type))
          for target, versions in sorted(targets.items()):
            print('    Target {} supports toolchains:'.format(target))
            for version, toolchains in sorted(versions.items()):
              print('      {}: {}'.format(version, ', '.join(sorted(toolchains))))
    elif args.target == 'discover':
      targets = kits[args.os]
      if not args.all:
        print('  {}'.format(', '.join(sorted(targets.keys()))))
      else:
        for target, versions in sorted(targets.items()):
          print('  Target {} supports toolchains:'.format(target))
          for version, toolchains in sorted(versions.items()):
            print('    {}: {}'.format(version, ', '.join(sorted(toolchains))))
    elif args.version == 'discover':
      versions = kits[args.os][args.target]
      if not args.all:
        print('  {}'.format(', '.join(map(str, sorted(versions.keys())))))
      else:
        for version, toolchains in sorted(versions.items()):
          print('  {}: {}'.format(version, ', '.join(sorted(toolchains))))
    elif args.toolchain == 'discover':
      toolchains = kits[args.os][args.target][args.version]
      print('  {}'.format(', '.join(sorted(toolchains))))

    sys.exit(0)

  url = build_url(args)

  info = get_info(url, args.version, args.toolchain)
  if info is None:
    sys.exit(1)

  name, version, archives = info
  download_and_extract(url + name + '/' + version, archives)


if __name__ == '__main__':
  try:
    main()
  except RuntimeError as error:
    print(error)
  except KeyboardInterrupt:
    print('Stopped by user')

