#!/usr/bin/env python3

import argparse
import platform
import requests
import semantic_version
import shutil
import subprocess
import sys
import urllib.request
from lxml import etree, html
from pathlib import Path
import os


BaseUrl = 'https://download.qt.io/online/qtsdkrepository/'
VersionBaseUrl = 'https://download.qt.io/official_releases/qt/'

# versions cache
__qt_avaliable_versions = []
# os types cache
__qt_avaliable_os_types = []
# targets cache
__qt_avaliable_targets = {}
# cache dirs for {BaseUrl}/{os_type}/{target}/
# E.g: https://download.qt.io/online/qtsdkrepository/linux_x64/android/
__qt_targets_dirs_cache = {}
# toolchains cache
__qt_avaliable_toolchains = {}

OsMap = {
  'macos': 'mac_x64',
  'linux': 'linux_x64',
  'windows': 'windows_x86'
}


def key_by_value(dict, value):
  return next((left for left, right in dict.items() if right == value), None)


def decode_version(v):
  v = list(v)
  major = v.pop(0)
  patch = v.pop() if len(v) > 1 else 0
  minor = ''.join(v)
  return '{}.{}.{}'.format(major, minor, patch)


def deduce_os():
  os_type = platform.system().lower()
  if os_type == 'darwin':
    os_type = 'macos'
  return os_type


def qt_avaliable_versions():
  global __qt_avaliable_versions
  if not __qt_avaliable_versions:
    major_minor_version_dirs = discover_dirs(VersionBaseUrl)
    for major_minor_version_dir in major_minor_version_dirs:
      full_version_dirs = discover_dirs(VersionBaseUrl + major_minor_version_dir)
      for version_dir in full_version_dirs:
        __qt_avaliable_versions.append(version_dir[:-1])
    __qt_avaliable_versions = list(map(str, sorted(map(semantic_version.Version, __qt_avaliable_versions))))

  return __qt_avaliable_versions


def qt_avaliable_targets(os_type):
  global __qt_avaliable_targets
  if not __qt_avaliable_targets.get(os_type):
    targets = discover_dirs(BaseUrl + os_type)
    __qt_avaliable_targets[os_type] = [target[:-1] for target in targets if target != 'root/']
  return __qt_avaliable_targets.get(os_type)


def qt_version_select(version_expression):
  if version_expression == 'latest':
    version_expression = '*'
  versions = [semantic_version.Version(v) for v in qt_avaliable_versions()]
  selected_ver = semantic_version.SimpleSpec(version_expression).select(versions)
  return str(selected_ver) if selected_ver else None


def qt_targets_dirs(os_type, target):
  global __qt_targets_dirs_cache
  if not __qt_targets_dirs_cache.get(os_type + '_' + target):
    # url like: https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/
    # {BaseUrl}{os_type}/{target}/
    targets_dirs = discover_dirs('{0}{1}/{2}/'.format(BaseUrl, os_type, target))
    __qt_targets_dirs_cache[os_type + '_' + target] = [d[:-1] for d in targets_dirs]
  return __qt_targets_dirs_cache[os_type + '_' + target]


def qt_avaliable_toolchains(os_type, target, version):
  global __qt_avaliable_toolchains
  if not __qt_avaliable_toolchains.get(os_type + '_' + target + '_' + version):
    major, minor, patch = version.split('.')
    # url like: https://download.qt.io/online/qtsdkrepository/linux_x64/desktop/qt5_5152/
    # {BaseUrl}{os_type}/{target}/qt{majro}_{majro}{minor}{patch}/
    toolchains_dir = 'qt{0}_{0}{1}{2}'.format(major, minor, patch)

    if toolchains_dir in qt_targets_dirs(os_type, target):
      toolchains = discover_dirs('{0}{1}/{2}/{3}/'.format(BaseUrl, os_type, target, toolchains_dir))
      toolchains = [toolchain.split('.')[2:] for toolchain in toolchains]
      toolchains = [toolchain[-1] for toolchain in toolchains if len(toolchain) > 0]
      toolchains = set([toolchain[:-1] for toolchain in toolchains if not toolchain.startswith('qt') and not toolchain.startswith('debug')])
      __qt_avaliable_toolchains[os_type + '_' + target + '_' + version] = toolchains
    else:
      __qt_avaliable_toolchains[os_type + '_' + target + '_' + version] = set({})
  return __qt_avaliable_toolchains[os_type + '_' + target + '_' + version]


def discover_dirs(url):
  reply = requests.get(url)
  page = html.fromstring(reply.content)
  items = page.xpath('//table//tr[position()>2]//a[not(starts-with(@href, "/"))]/@href')
  return [item for item in items if item.endswith('/')]


def discover_kits(args):
  os_dict = {}
  os_types = OsMap.values()
  for os_type in os_types:
    human_os = key_by_value(OsMap, os_type)
    current_os = human_os if human_os is not None else os_type
    os_dict[current_os] = None

    if not (args.os == 'discover' and args.all or args.os != 'discover' and args.os in [os_type, human_os]):
      continue

    targets_dict = {}
    for target in qt_avaliable_targets(os_type):
      targets_dict[target] = None

      if not (args.target == 'discover' and args.all or args.target != 'discover' and args.target == target):
        continue

      versions_dict = {}
      if args.version == 'discover':
        for version in qt_avaliable_versions():
          versions_dict[version] = None
          if args.all:
            versions_dict[version] = qt_avaliable_toolchains(os_type, target, version)
      else:
        check_versions(args)
        version = qt_version_select(args.version)
        versions_dict[version] = qt_avaliable_toolchains(os_type, target, version)

      targets_dict[target] = versions_dict

    os_dict[current_os] = targets_dict

  return os_dict


def build_url(args):
  ver = args.version.replace('.', '')
  return BaseUrl + '{}/{}/qt5_{}/'.format(OsMap[args.os], args.target, ver)


def get_info(url, version, toolchain):
  reply = requests.get(url + "Updates.xml")
  update_xml = etree.fromstring(reply.content)

  ver = version.replace('.', '')

  for package in update_xml.xpath('//PackageUpdate'):
    name = package.xpath('Name/text()')[0]
    if name.startswith('qt.') and name.endswith('.{}.{}'.format(ver, toolchain)):
      version = package.xpath('Version/text()')[0]
      archives = package.xpath('DownloadableArchives/text()')[0].split(', ')
      return (name, version, archives)

  print('Update.xml does not contain proper entry for Qt kit', file=sys.stderr)
  return None


def download_and_extract(archives_url, archives, modules, output):
  for archive in archives:
    module = archive.split('-')[0]
    if len(modules) != 0 and (module not in modules):
      continue
    try:
      print('Downloading module {}... '.format(module), end='', flush=True)
      with urllib.request.urlopen(archives_url + archive) as response, open(archive, 'wb') as out_file:
        shutil.copyfileobj(response, out_file)

      print('\rExtracting module {}... '.format(module), end='', flush=True)
      subprocess.run('7z x {0} -o{1}'.format(archive, output), shell=True, check=True,
        stdout=subprocess.PIPE, stderr=subprocess.PIPE)
      print('\rInstalled module {} successfully'.format(module))
    except subprocess.CalledProcessError as e:
      print('Error: {}'.format(e))

      os_type = deduce_os()
      suggestion = ''
      if os_type == 'linux':
        suggestion = ' Run sudo apt install p7zip-full on Ubuntu'
      elif os_type == 'macos':
        suggestion = ' Run brew install p7zip on macOS'
        
      raise RuntimeError('Check that 7z command is in your PATH.{}'.format(suggestion))
    except KeyboardInterrupt:
      print('Interrupted')
      raise KeyboardInterrupt
    finally:
      Path(archive).unlink()

  print('Finished installation')


def show_discover_context(args, parser):
  if args.os != 'discover':
    if args.os == 'auto':
      args.os = deduce_os()

    print('OS type: {}'.format(args.os))

  if args.target != 'discover':
    print('Target: {}'.format(args.target))

  if args.version != 'discover':
    version = ''
    if check_versions(args):
      kits = discover_kits(args)
      check_os_type(args, kits)
      targets = kits[args.os]
      check_targets(args, targets)
      version = qt_version_select(args.version)
    else:
      print('Wrong version: {}. Should follow Semantic Versioning format: major.minor.patch\n'.format(args.version), file=sys.stderr)
      parser.print_help()
      sys.exit(1)

    print('Qt version: {}'.format(version))

  if args.toolchain != 'discover':
    print('Toolchain: {}'.format(args.toolchain))


def show_discovered_parameters(args, params, labels):
  print('Discovering available ', end='')
  
  discoverables = []
  for index, param in enumerate(params):
    if param == 'discover':
      discoverables.append(labels[index])

  if not args.all:
    discoverables = discoverables[:1]

  if len(discoverables) == 1:
    print('{}...'.format(discoverables[0]), end='', flush=True)
  elif len(discoverables) == 2:
    print('{}...'.format(' and '.join(discoverables)), end='', flush=True)
  else:
    print('{}, and {}...'.format(', '.join(discoverables[:-1]), discoverables[-1]), end='', flush=True)


def show_os_types_only(kits):
  print('  Choose from: {}'.format(', '.join(sorted(kits.keys()))))


def show_targets_only(targets):
  print('  Choose from: {}'.format(', '.join(sorted(targets.keys()))))


def show_versions_only():
  print('  Choose from: {}'.format(', '.join(qt_avaliable_versions())))


def show_toolchains_only(toolchains):
  print('  Choose from: {}'.format(', '.join(sorted(toolchains))))


def check_os_type(args, kits):
  if not args.os in kits:
    print('  Unknown OS type: {}'.format(args.os))
    show_os_types_only(kits)
    sys.exit(1)


def check_targets(args, targets):
  if not args.target in targets:
    print('  Unknown target: {}'.format(args.target))
    show_targets_only(targets)
    sys.exit(1)


def check_versions(args):
  if not qt_version_select(args.version):
    print('  Unknown version: {}'.format(args.version))
    show_versions_only()
    sys.exit(1)
  return True


def check_toolchains(args, toolchains):
  if not args.toolchain in toolchains:
    print('  Unknown toolchain: {}'.format(args.toolchain))
    show_toolchains_only(toolchains)
    sys.exit(1)

def show_os_types_and_all(kits, indent = 0):
  for os_type, targets in kits.items():
    print('  {}{}:'.format('  ' * indent, os_type))
    show_targets_and_all(targets, indent + 1)


def show_targets_and_all(targets, indent = 0):
  for target, versions in sorted(targets.items()):
    print('  {}Target {} supports toolchains:'.format('  ' * indent, target))
    show_versions_and_all(versions, indent + 1)


def show_versions_and_all(versions, indent = 0):
  for version, toolchains in sorted(versions.items()):
    if toolchains:
      print('  {}{}: {}'.format('  ' * indent, version, ', '.join(sorted(toolchains))))


def show_discovery_results(args, kits):
  print(' Done')

  if args.os == 'discover':
    if not args.all:
      show_os_types_only(kits)
    else:
      show_os_types_and_all(kits)
  elif args.target == 'discover':
    check_os_type(args, kits)
    targets = kits[args.os]
    if not args.all:
      show_targets_only(targets)
    else:
      show_targets_and_all(targets)
  elif args.version == 'discover':
    check_os_type(args, kits)
    targets = kits[args.os]
    check_targets(args, targets)
    versions = targets[args.target]
    if not args.all:
      show_versions_only()
    else:
      show_versions_and_all(versions)
  elif args.toolchain == 'discover':
    check_os_type(args, kits)
    targets = kits[args.os]
    check_targets(args, targets)
    check_versions(args)
    version = qt_version_select(args.version)
    versions = targets[args.target]
    toolchains = versions[version]
    show_toolchains_only(toolchains)
  else:
    check_os_type(args, kits)
    targets = kits[args.os]
    check_targets(args, targets)
    versions = targets[args.target]
    check_versions(args)
    version = qt_version_select(args.version)
    toolchains = versions[version]
    check_toolchains(args, toolchains)


def verify_parameters(args):
  print('Verifying arguments...', end='')
  kits = discover_kits(args)
  show_discovery_results(args, kits)


def main():
  parser = argparse.ArgumentParser(description='Qt downloader',
    formatter_class=argparse.ArgumentDefaultsHelpFormatter)
  parser.add_argument('os', nargs='?', default='discover', help='Operating system type: {}, auto, or discovered one. Omit this to discover available OS types'.format(', '.join(OsMap.keys())))
  parser.add_argument('target', nargs='?', default='discover', help='Target platform. Omit this to discover available targets')
  parser.add_argument('version', nargs='?', default='discover', help='Qt version conforming to Semantic Versioning select expression, E.g: 5, 5.14, 5.12.10, ... Use \'latest\' to get most up to date version. Omit this to discover available versions.')
  parser.add_argument('toolchain', nargs='?', default='discover', help='Toolchain to use. Omit this to discover available toolchains')
  parser.add_argument('--all', '-a', action='store_true', help='Discover allowed values for all missing arguments')
  parser.add_argument('--modules', '-m', nargs='*', default=[], help='Download only selected modules')
  parser.add_argument('--output', '-o', default='.', help='Output directory')
  args = parser.parse_args()

  show_discover_context(args, parser)

  params = [args.os, args.target, args.version, args.toolchain]
  labels = ['OS types', 'targets', 'Qt versions', 'toolchains']
  if 'discover' in params:
    show_discovered_parameters(args, params, labels)
    kits = discover_kits(args)
    show_discovery_results(args, kits)
    sys.exit(0)
  else:
    verify_parameters(args)
    args.version = qt_version_select(args.version)
    url = build_url(args)

    info = get_info(url, args.version, args.toolchain)
    if info is None:
      sys.exit(1)

    name, version, archives = info
    download_and_extract(url + name + '/' + version, archives, args.modules, args.output)


if __name__ == '__main__':
  try:
    main()
  except IOError as error:
    print(error)
  except RuntimeError as error:
    print(error)
  except KeyboardInterrupt:
    print('Stopped by user')
